# Generated by Django 4.2.7 on 2025-08-06 17:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('description', models.TextField(verbose_name='description')),
                ('address', models.TextField(verbose_name='adresse')),
                ('city', models.CharField(default='Nouakchott', max_length=100, verbose_name='ville')),
                ('country', models.CharField(default='Mauritanie', max_length=100, verbose_name='pays')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('apartment_type', models.CharField(choices=[('studio', 'Studio'), ('one_bedroom', '1 chambre'), ('two_bedroom', '2 chambres'), ('three_bedroom', '3 chambres'), ('four_bedroom', '4 chambres'), ('penthouse', 'Penthouse'), ('villa', 'Villa')], max_length=20, verbose_name="type d'appartement")),
                ('property_type', models.CharField(choices=[('apartment', 'Appartement'), ('house', 'Maison'), ('villa', 'Villa'), ('studio', 'Studio')], max_length=20, verbose_name='type de propriété')),
                ('bedrooms', models.IntegerField(default=1, verbose_name='chambres')),
                ('bathrooms', models.IntegerField(default=1, verbose_name='salles de bain')),
                ('max_guests', models.IntegerField(default=2, verbose_name='nombre maximum de voyageurs')),
                ('surface_area', models.IntegerField(blank=True, null=True, verbose_name='surface en m²')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='étage')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix par nuit')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='pourcentage de réduction')),
                ('cleaning_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='frais de ménage')),
                ('service_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='frais de service')),
                ('wifi', models.BooleanField(default=True, verbose_name='Wi-Fi')),
                ('air_conditioning', models.BooleanField(default=True, verbose_name='climatisation')),
                ('heating', models.BooleanField(default=False, verbose_name='chauffage')),
                ('kitchen', models.BooleanField(default=True, verbose_name='cuisine équipée')),
                ('washing_machine', models.BooleanField(default=False, verbose_name='machine à laver')),
                ('dryer', models.BooleanField(default=False, verbose_name='sèche-linge')),
                ('tv', models.BooleanField(default=True, verbose_name='télévision')),
                ('balcony', models.BooleanField(default=False, verbose_name='balcon')),
                ('terrace', models.BooleanField(default=False, verbose_name='terrasse')),
                ('garden', models.BooleanField(default=False, verbose_name='jardin')),
                ('parking', models.BooleanField(default=False, verbose_name='parking')),
                ('elevator', models.BooleanField(default=False, verbose_name='ascenseur')),
                ('pool', models.BooleanField(default=False, verbose_name='piscine')),
                ('gym', models.BooleanField(default=False, verbose_name='salle de sport')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='note moyenne')),
                ('total_reviews', models.IntegerField(default=0, verbose_name="nombre total d'avis")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_featured', models.BooleanField(default=False, verbose_name='mis en avant')),
                ('is_instant_bookable', models.BooleanField(default=True, verbose_name='réservation instantanée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'appartement',
                'verbose_name_plural': 'appartements',
                'ordering': ['-rating', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApartmentAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('is_available', models.BooleanField(default=True, verbose_name='disponible')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='prix spécial')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': "disponibilité d'appartement",
                'verbose_name_plural': "disponibilités d'appartements",
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='apartments/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='légende')),
                ('is_primary', models.BooleanField(default=False, verbose_name='image principale')),
                ('order', models.IntegerField(default=0, verbose_name='ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'verbose_name': "image d'appartement",
                'verbose_name_plural': "images d'appartements",
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApartmentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='note')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('comment', models.TextField(verbose_name='commentaire')),
                ('is_verified', models.BooleanField(default=False, verbose_name='vérifié')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='apartments.apartment')),
            ],
            options={
                'verbose_name': "avis d'appartement",
                'verbose_name_plural': "avis d'appartements",
                'ordering': ['-created_at'],
            },
        ),
    ]
