# Generated by Django 4.2.7 on 2025-08-12 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentimage',
            name='image',
            field=models.URLField(max_length=500, verbose_name='image'),
        ),
    ]
