# Generated by Django 4.2.7 on 2025-08-06 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('description', models.TextField(verbose_name='description')),
                ('free_cancellation_hours', models.IntegerField(default=24, help_text="Nombre d'heures avant l'arrivée pour une annulation gratuite", verbose_name="heures d'annulation gratuite")),
                ('refund_percentage_24h', models.DecimalField(decimal_places=2, default=100.0, help_text="Pourcentage de remboursement 24h avant l'arrivée", max_digits=5, verbose_name='remboursement 24h avant')),
                ('refund_percentage_48h', models.DecimalField(decimal_places=2, default=50.0, help_text="Pourcentage de remboursement 48h avant l'arrivée", max_digits=5, verbose_name='remboursement 48h avant')),
                ('refund_percentage_72h', models.DecimalField(decimal_places=2, default=25.0, help_text="Pourcentage de remboursement 72h avant l'arrivée", max_digits=5, verbose_name='remboursement 72h avant')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'verbose_name': "politique d'annulation",
                'verbose_name_plural': "politiques d'annulation",
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Carte de crédit'), ('debit_card', 'Carte de débit'), ('bank_transfer', 'Virement bancaire'), ('mobile_money', 'Mobile Money'), ('cash', 'Espèces'), ('paypal', 'PayPal')], max_length=20, verbose_name='méthode de paiement')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='statut')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID de transaction')),
                ('payment_gateway', models.CharField(blank=True, max_length=50, verbose_name='passerelle de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='traité le')),
                ('error_message', models.TextField(blank=True, verbose_name="message d'erreur")),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.CharField(max_length=20, unique=True, verbose_name='numéro de réservation')),
                ('check_in_date', models.DateField(verbose_name="date d'arrivée")),
                ('check_out_date', models.DateField(verbose_name='date de départ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('guest_name', models.CharField(max_length=200, verbose_name='nom du voyageur')),
                ('guest_email', models.EmailField(max_length=254, verbose_name='email du voyageur')),
                ('guest_phone', models.CharField(max_length=20, verbose_name='téléphone du voyageur')),
                ('number_of_guests', models.IntegerField(default=1, verbose_name='nombre de voyageurs')),
                ('special_requests', models.TextField(blank=True, verbose_name='demandes spéciales')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant total')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='montant des taxes')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='montant de la réduction')),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant final')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée'), ('completed', 'Terminée'), ('refunded', 'Remboursée')], default='pending', max_length=20, verbose_name='statut')),
                ('payment_status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payée'), ('failed', 'Échouée'), ('refunded', 'Remboursée')], default='pending', max_length=20, verbose_name='statut du paiement')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='annulée')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name="raison de l'annulation")),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='annulée le')),
            ],
            options={
                'verbose_name': 'réservation',
                'verbose_name_plural': 'réservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApartmentReservation',
            fields=[
                ('reservation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.reservation')),
            ],
            options={
                'verbose_name': "réservation d'appartement",
                'verbose_name_plural': "réservations d'appartements",
            },
            bases=('reservations.reservation',),
        ),
        migrations.CreateModel(
            name='HotelReservation',
            fields=[
                ('reservation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.reservation')),
            ],
            options={
                'verbose_name': "réservation d'hôtel",
                'verbose_name_plural': "réservations d'hôtels",
            },
            bases=('reservations.reservation',),
        ),
    ]
