# Generated by Django 4.2.7 on 2025-08-06 17:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('description', models.TextField(verbose_name='description')),
                ('address', models.TextField(verbose_name='adresse')),
                ('city', models.CharField(default='Nouakchott', max_length=100, verbose_name='ville')),
                ('country', models.CharField(default='Mauritanie', max_length=100, verbose_name='pays')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('phone', models.CharField(max_length=20, verbose_name='téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('website', models.URLField(blank=True, verbose_name='site web')),
                ('stars', models.IntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')], default=3, verbose_name='étoiles')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='note moyenne')),
                ('total_reviews', models.IntegerField(default=0, verbose_name="nombre total d'avis")),
                ('wifi', models.BooleanField(default=True, verbose_name='Wi-Fi')),
                ('air_conditioning', models.BooleanField(default=True, verbose_name='climatisation')),
                ('restaurant', models.BooleanField(default=False, verbose_name='restaurant')),
                ('pool', models.BooleanField(default=False, verbose_name='piscine')),
                ('gym', models.BooleanField(default=False, verbose_name='salle de sport')),
                ('spa', models.BooleanField(default=False, verbose_name='spa')),
                ('parking', models.BooleanField(default=True, verbose_name='parking')),
                ('airport_shuttle', models.BooleanField(default=False, verbose_name='navette aéroport')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_featured', models.BooleanField(default=False, verbose_name='mis en avant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'hôtel',
                'verbose_name_plural': 'hôtels',
                'ordering': ['-rating', '-stars', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotels/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='légende')),
                ('is_primary', models.BooleanField(default=False, verbose_name='image principale')),
                ('order', models.IntegerField(default=0, verbose_name='ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'verbose_name': "image d'hôtel",
                'verbose_name_plural': "images d'hôtels",
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('category', models.CharField(choices=[('single', 'Chambre simple'), ('double', 'Chambre double'), ('twin', 'Chambre twin'), ('triple', 'Chambre triple'), ('suite', 'Suite'), ('family', 'Chambre familiale'), ('luxury', 'Chambre de luxe')], max_length=20, verbose_name='catégorie')),
                ('description', models.TextField(verbose_name='description')),
                ('capacity', models.IntegerField(default=2, verbose_name='capacité')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix par nuit')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='pourcentage de réduction')),
                ('is_available', models.BooleanField(default=True, verbose_name='disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'type de chambre',
                'verbose_name_plural': 'types de chambres',
                'ordering': ['price_per_night'],
            },
        ),
        migrations.CreateModel(
            name='HotelReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='note')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('comment', models.TextField(verbose_name='commentaire')),
                ('is_verified', models.BooleanField(default=False, verbose_name='vérifié')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hotels.hotel')),
            ],
            options={
                'verbose_name': "avis d'hôtel",
                'verbose_name_plural': "avis d'hôtels",
                'ordering': ['-created_at'],
            },
        ),
    ]
