# Generated by Django 4.2.7 on 2025-08-12 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_hotelimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='website',
        ),
    ]
