# Generated by Django 4.2.7 on 2025-08-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'OTP de réinitialisation',
                'verbose_name_plural': 'OTPs de réinitialisation',
                'indexes': [models.Index(fields=['phone', 'is_used'], name='users_passw_phone_28c333_idx')],
            },
        ),
    ]
