# Generated by Django 4.2.7 on 2025-08-10 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_profile_picture_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture_url',
        ),
    ]
