[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn reservation_project.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.variables]
PYTHON_VERSION = "3.11.7" 