databases:
  - name: reservation-postgres
    databaseName: reservation_db
    user: reservation_user
    plan: free

services:
  - type: web
    name: reservation-backend
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn reservation_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: reservation-postgres
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false 